# Generated by Django 4.2 on 2023-05-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('leader', '計畫總主持人'), ('executor', '計畫執行人員'), ('other', '其他人員')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'Contact',
            },
        ),
    ]
