# Generated by Django 4.2 on 2023-07-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='newsAttachments')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsAttachments', to='user.news')),
            ],
            options={
                'db_table': 'NewsAttachment',
            },
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
