# Generated by Django 4.2 on 2023-07-14 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_newsattachment_delete_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='user_id',
            new_name='user',
        ),
    ]
