# Generated by Django 4.2 on 2023-07-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_user_id_news_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'FormLink',
            },
        ),
        migrations.CreateModel(
            name='FormLinkAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='formLinkAttachments')),
                ('form_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formLinkAttachments', to='user.formlink')),
            ],
            options={
                'db_table': 'FormLinkAttachment',
            },
        ),
    ]
