# Generated by Django 4.2 on 2023-07-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_formlink_formlinkattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='formlink',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
