# Generated by Django 4.2 on 2023-07-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_news_image_newsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newsCoverImages')),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newsCoverImage', to='user.news')),
            ],
            options={
                'db_table': 'NewsCoverImage',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_cover_image', to='user.newscoverimage'),
        ),
    ]
