# Generated by Django 4.1.1 on 2023-08-01 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_newscoverimage_news_cover_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ecologicalObservation", "生態觀測"),
                            ("environmentalObservation", "環境觀測"),
                            ("socialObservation", "社會觀測"),
                        ],
                        max_length=200,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="aboutImage")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
            ],
            options={
                "db_table": "About",
            },
        ),
        migrations.CreateModel(
            name="AboutAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file", models.FileField(upload_to="aboutAttachments")),
                ("image", models.ImageField(upload_to="aboutAttachments")),
                ("created_at", models.DateField(auto_now_add=True)),
                ("updated_at", models.DateField(auto_now=True)),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aboutAttachments",
                        to="user.about",
                    ),
                ),
            ],
            options={
                "db_table": "AboutAttachment",
            },
        ),
    ]
