# Generated by Django 4.2 on 2023-08-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_aboutattachment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='aboutAttachments'),
        ),
        migrations.AlterField(
            model_name='aboutattachment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='aboutAttachments'),
        ),
    ]
