# Generated by Django 4.2 on 2023-08-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_downloadapply_downloadrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadapply',
            name='filename',
            field=models.CharField(max_length=255, blank=True, null=True),
        ),
    ]
