# Generated by Django 4.2 on 2023-08-11 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_downloadapply_filename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutAttachment',
        ),
    ]
