# Generated by Django 4.2 on 2023-08-11 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_delete_aboutattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='aboutAttachments')),
                ('image', models.ImageField(blank=True, null=True, upload_to='aboutAttachments')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aboutAttachments', to='user.about')),
            ],
            options={
                'db_table': 'AboutAttachment',
            },
        ),
    ]
