# Generated by Django 4.2 on 2023-10-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_about_content_en_about_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
