# Generated by Django 4.1.1 on 2023-12-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0025_alter_about_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="aboutImage"),
        ),
    ]
