# Generated by Django 4.1.1 on 2023-12-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0027_myuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="is_regular_user",
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
