# Generated by Django 4.1.1 on 2024-01-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0028_myuser_is_regular_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="qatag",
            name="title_en",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="answer_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="question_en",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
