# Generated by Django 4.1.1 on 2024-01-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0029_qatag_title_en_questionanswer_answer_en_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="contact",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="content",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="content_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="unit",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="contact",
            name="unit_en",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
