# Generated by Django 4.1.1 on 2024-09-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_contact_contact_alter_contact_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
