# Generated by Django 4.1.1 on 2025-03-17 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_socialeconomyvisitors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialeconomyvisitors',
            old_name='vistors',
            new_name='visitors',
        ),
    ]
