# Generated by Django 4.1.1 on 2025-03-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_rename_vistors_socialeconomyvisitors_visitors'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_social_project_staff',
            field=models.BooleanField(default=False),
        ),
    ]
