# Generated by Django 4.1.1 on 2025-07-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_myuser_is_social_project_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literature',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='literature',
            name='author',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='literature',
            name='category',
            field=models.CharField(choices=[('RESEARCH', '研究報告'), ('JOURNAL', '期刊論文'), ('THESIS', '學術論文'), ('BOOK', '書籍'), ('EIA', '環評報告')], default='BOOK', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='literature',
            name='unit',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='literature',
            name='url',
            field=models.URLField(default='https://www.grb.gov.tw/search/planDetail?id=16558647'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='literature',
            name='year',
            field=models.IntegerField(default=1996),
            preserve_default=False,
        ),
    ]
