# Generated by Django 4.1.1 on 2025-07-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_alter_literature_author_alter_literature_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='author',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
