# Generated by Django 4.1.1 on 2025-07-24 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_literature_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literature',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
