# Generated by Django 4.1.1 on 2025-12-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_alter_literature_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='relate',
            field=models.CharField(choices=[('NATURE', '自然相關'), ('SOCIAL', '社會相關'), ('HYDROLOGY', '水文相關'), ('LITERATURE', '文學相關'), ('ENERGY', '能源建設相關')], default='NATURE', max_length=20),
            preserve_default=False,
        ),
    ]
