version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 8001
    restart: always

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
      - 8888:8888
#      - 443:443
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../ltser-lyudao-volumes/frontend:/frontend
      - ../ltser-lyudao-volumes/certbot/conf:/etc/letsencrypt
      - ../ltser-lyudao-volumes/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ../ltser-lyudao-volumes/certbot/conf:/etc/letsencrypt
      - ../ltser-lyudao-volumes/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
  db:
    restart: always
