# Generated by Django 4.2 on 2023-06-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('resourceName', models.CharField(max_length=255)),
                ('eventDate', models.DateTimeField()),
                ('locationID', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('stationAttribute', models.CharField(max_length=255)),
                ('decimalLongitude', models.FloatField()),
                ('decimalLatitude', models.FloatField()),
                ('stationAddress', models.CharField(max_length=255)),
                ('PAR', models.FloatField()),
                ('solarRadiation', models.FloatField()),
                ('windDirection', models.IntegerField()),
                ('pressure', models.FloatField()),
                ('windSpeed', models.FloatField()),
                ('gustSpeed', models.FloatField()),
                ('airTemperature', models.FloatField()),
                ('RH', models.FloatField()),
                ('precipitation', models.FloatField()),
            ],
            options={
                'db_table': 'WeatherData',
            },
        ),
    ]
