# Generated by Django 4.2 on 2023-06-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='windSpeed',
            field=models.FloatField(null=True),
        ),
    ]
