# Generated by Django 4.2 on 2023-06-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_weatherdata_windspeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='RH',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='airTemperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='gustSpeed',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='precipitation',
            field=models.FloatField(null=True),
        ),
    ]
