# Generated by Django 4.2 on 2023-06-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seatemperatureck2023_seatemperaturedbs2023_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=50)),
                ('eventID', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('eventDate', models.DateField()),
                ('locationID', models.CharField(max_length=50)),
                ('verbatimLocality', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('verbatimDepth', models.CharField(max_length=50)),
                ('decimalLatitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('decimalLongitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('replicate', models.IntegerField()),
                ('scientificName', models.CharField(max_length=50)),
                ('taxonRank', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('identificationRemarks', models.CharField(blank=True, max_length=50)),
                ('measurementType', models.CharField(max_length=50)),
                ('measurementValue', models.FloatField()),
                ('measurementUnit', models.CharField(max_length=50)),
                ('individualCount', models.IntegerField()),
                ('recordedBy', models.CharField(max_length=50)),
                ('identifiedBy', models.CharField(max_length=50)),
                ('samplingProtocol', models.CharField(max_length=50)),
                ('sampleSizeValue', models.FloatField()),
                ('sampleSizeUnit', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CoralData',
            },
        ),
    ]
