# Generated by Django 4.2 on 2023-06-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_coraldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coraldata',
            name='eventDate',
            field=models.DateTimeField(),
        ),
    ]
