# Generated by Django 4.2 on 2023-06-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_coraldata_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coraldata',
            name='identificationRemarks',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
