# Generated by Django 4.2 on 2023-06-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_coraldata_identificationremarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=50)),
                ('eventID', models.CharField(max_length=50)),
                ('eventDate', models.DateField()),
                ('locationID', models.IntegerField()),
                ('habitat', models.CharField(max_length=50)),
                ('samplingProtocol', models.CharField(max_length=50)),
                ('sampleSizeValue', models.IntegerField()),
                ('sampleSizeUnit', models.CharField(max_length=50)),
                ('decimalLatitude', models.FloatField()),
                ('decimalLongitude', models.FloatField()),
                ('coordinatePrecision', models.FloatField()),
                ('verbatimElevation', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('scientificName', models.CharField(max_length=50)),
                ('vernacularName', models.CharField(max_length=50)),
                ('taxonRank', models.CharField(max_length=50)),
                ('recordedBy', models.CharField(max_length=50)),
                ('identifiedBy', models.CharField(max_length=50)),
                ('measurementType', models.CharField(max_length=50)),
                ('measurementValue', models.FloatField()),
                ('measurementUnit', models.CharField(max_length=50)),
                ('layer', models.CharField(max_length=50)),
                ('measurementDeterminedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'PlantData',
            },
        ),
    ]
