# Generated by Django 4.2 on 2023-06-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_plantdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='eventDate',
            field=models.DateTimeField(),
        ),
    ]
