# Generated by Django 4.2 on 2023-06-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_plantdata_eventdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdNetSoundBS2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('eventID', models.CharField(max_length=255)),
                ('species_list', models.CharField(blank=True, max_length=255, null=True)),
                ('scientificName', models.CharField(max_length=255)),
                ('taxonRank', models.CharField(max_length=255)),
                ('vernacularName', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('time_begin', models.IntegerField()),
                ('time_end', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('associatedMedia', models.CharField(max_length=255)),
                ('week', models.IntegerField()),
                ('overlap', models.IntegerField()),
                ('sensitivity', models.IntegerField()),
                ('min_conf', models.FloatField()),
                ('measurementDeterminedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'BirdNetSoundBS2023',
            },
        ),
        migrations.CreateModel(
            name='BirdNetSoundGST2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('eventID', models.CharField(max_length=255)),
                ('species_list', models.CharField(blank=True, max_length=255, null=True)),
                ('scientificName', models.CharField(max_length=255)),
                ('taxonRank', models.CharField(max_length=255)),
                ('vernacularName', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('time_begin', models.IntegerField()),
                ('time_end', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('associatedMedia', models.CharField(max_length=255)),
                ('week', models.IntegerField()),
                ('overlap', models.IntegerField()),
                ('sensitivity', models.IntegerField()),
                ('min_conf', models.FloatField()),
                ('measurementDeterminedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'BirdNetSoundGST2023',
            },
        ),
        migrations.CreateModel(
            name='BirdNetSoundLH2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('eventID', models.CharField(max_length=255)),
                ('species_list', models.CharField(blank=True, max_length=255, null=True)),
                ('scientificName', models.CharField(max_length=255)),
                ('taxonRank', models.CharField(max_length=255)),
                ('vernacularName', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('time_begin', models.IntegerField()),
                ('time_end', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('associatedMedia', models.CharField(max_length=255)),
                ('week', models.IntegerField()),
                ('overlap', models.IntegerField()),
                ('sensitivity', models.IntegerField()),
                ('min_conf', models.FloatField()),
                ('measurementDeterminedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'BirdNetSoundLH2023',
            },
        ),
        migrations.CreateModel(
            name='BirdNetSoundYZH2023',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('eventID', models.CharField(max_length=255)),
                ('species_list', models.CharField(blank=True, max_length=255, null=True)),
                ('scientificName', models.CharField(max_length=255)),
                ('taxonRank', models.CharField(max_length=255)),
                ('vernacularName', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('time_begin', models.IntegerField()),
                ('time_end', models.IntegerField()),
                ('confidence', models.FloatField()),
                ('associatedMedia', models.CharField(max_length=255)),
                ('week', models.IntegerField()),
                ('overlap', models.IntegerField()),
                ('sensitivity', models.IntegerField()),
                ('min_conf', models.FloatField()),
                ('measurementDeterminedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'BirdNetSoundYZH2023',
            },
        ),
    ]
