# Generated by Django 4.2 on 2023-06-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_birdnetsoundbs2023_birdnetsoundgst2023_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('eventID', models.CharField(max_length=255)),
                ('eventDate', models.DateTimeField()),
                ('season', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('region', models.CharField(max_length=255)),
                ('locationID', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('verbatimDepth', models.CharField(max_length=255)),
                ('replicate', models.IntegerField()),
                ('sampleSizeValue', models.IntegerField()),
                ('sampleSizeUnit', models.CharField(max_length=255)),
                ('fieldNotes', models.CharField(max_length=255)),
                ('recordedBy', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('ScientificName', models.CharField(max_length=255)),
                ('taxonRank', models.CharField(max_length=255)),
                ('bodyLength', models.FloatField()),
                ('samplingProtocol', models.CharField(max_length=255)),
                ('individualCount', models.IntegerField()),
                ('identifiedBy', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'FishData',
            },
        ),
    ]
