# Generated by Django 4.2 on 2023-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_zoobenthosdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='habitat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='informationWithheld',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
