# Generated by Django 4.2 on 2023-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_zoobenthosdata_habitat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='eventDate',
            field=models.DateTimeField(),
        ),
    ]
