# Generated by Django 4.2 on 2023-07-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_zoobenthosdata_eventdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='family',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
