# Generated by Django 4.2 on 2023-07-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_zoobenthosdata_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='family_c',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='samplingProtocol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='scientificName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='taxonRank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='vernacularName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
