# Generated by Django 4.2 on 2023-07-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_zoobenthosdata_family_c_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fishdata',
            old_name='ScientificName',
            new_name='scientificName',
        ),
    ]
