# Generated by Django 4.2 on 2023-07-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_scientificname_fishdata_scientificname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerreSoundIndexBS2023',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataID', models.CharField(max_length=200)),
                ('eventID', models.CharField(max_length=200)),
                ('sh', models.FloatField()),
                ('th', models.FloatField()),
                ('H', models.FloatField()),
                ('ACI', models.FloatField()),
                ('ADI', models.FloatField()),
                ('AEI', models.FloatField()),
                ('BI', models.FloatField()),
                ('NDSI', models.FloatField()),
                ('associatedMedia', models.CharField(max_length=200)),
                ('min', models.FloatField()),
                ('sec', models.FloatField()),
                ('measurementDeterminedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'TerreSoundIndexBS2023',
            },
        ),
        migrations.CreateModel(
            name='TerreSoundIndexGST2023',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataID', models.CharField(max_length=200)),
                ('eventID', models.CharField(max_length=200)),
                ('sh', models.FloatField()),
                ('th', models.FloatField()),
                ('H', models.FloatField()),
                ('ACI', models.FloatField()),
                ('ADI', models.FloatField()),
                ('AEI', models.FloatField()),
                ('BI', models.FloatField()),
                ('NDSI', models.FloatField()),
                ('associatedMedia', models.CharField(max_length=200)),
                ('min', models.FloatField()),
                ('sec', models.FloatField()),
                ('measurementDeterminedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'TerreSoundIndexGST2023',
            },
        ),
        migrations.CreateModel(
            name='TerreSoundIndexLH2023',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataID', models.CharField(max_length=200)),
                ('eventID', models.CharField(max_length=200)),
                ('sh', models.FloatField()),
                ('th', models.FloatField()),
                ('H', models.FloatField()),
                ('ACI', models.FloatField()),
                ('ADI', models.FloatField()),
                ('AEI', models.FloatField()),
                ('BI', models.FloatField()),
                ('NDSI', models.FloatField()),
                ('associatedMedia', models.CharField(max_length=200)),
                ('min', models.FloatField()),
                ('sec', models.FloatField()),
                ('measurementDeterminedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'TerreSoundIndexLH2023',
            },
        ),
        migrations.CreateModel(
            name='TerreSoundIndexYZH2023',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataID', models.CharField(max_length=200)),
                ('eventID', models.CharField(max_length=200)),
                ('sh', models.FloatField()),
                ('th', models.FloatField()),
                ('H', models.FloatField()),
                ('ACI', models.FloatField()),
                ('ADI', models.FloatField()),
                ('AEI', models.FloatField()),
                ('BI', models.FloatField()),
                ('NDSI', models.FloatField()),
                ('associatedMedia', models.CharField(max_length=200)),
                ('min', models.FloatField()),
                ('sec', models.FloatField()),
                ('measurementDeterminedDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'TerreSoundIndexYZH2023',
            },
        ),
    ]
