# Generated by Django 4.2 on 2023-07-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_terresoundindexbs2023_terresoundindexgst2023_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terresoundindexbs2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='terresoundindexgst2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='terresoundindexlh2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='terresoundindexyzh2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
    ]
