# Generated by Django 4.2 on 2023-07-16 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_rename_measurementdetermineddate_terresoundindexbs2023_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birdnetsoundbs2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='birdnetsoundgst2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='birdnetsoundlh2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='birdnetsoundyzh2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='coraldata',
            old_name='eventDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='fishdata',
            old_name='eventDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='seatemperatureck2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='seatemperaturedbs2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='seatemperaturegg2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='seatemperaturegw2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='seatemperaturenl2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='seatemperaturesl2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='seatemperaturewqg2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='seatemperatureyzh2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='seatemperaturezp2023',
            old_name='measurementDeterminedDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='weatherdata',
            old_name='eventDate',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='zoobenthosdata',
            old_name='eventDate',
            new_name='time',
        ),
    ]
