# Generated by Django 4.2 on 2023-07-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_rename_measurementdetermineddate_birdnetsoundbs2023_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantdata',
            old_name='eventDate',
            new_name='time',
        ),
    ]
