# Generated by Django 4.1.1 on 2023-08-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_rename_eventdate_plantdata_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataID", models.CharField(max_length=255)),
                ("eventID", models.CharField(max_length=255)),
                ("resourceName", models.CharField(max_length=255)),
                ("time", models.DateField()),
                ("locationID", models.CharField(max_length=255)),
                ("locality", models.CharField(max_length=255)),
                ("verbatimDepth", models.FloatField()),
                ("waterTemperature", models.FloatField()),
                ("DO", models.FloatField(blank=True, null=True)),
                ("conductivity", models.FloatField()),
                ("salinity", models.FloatField()),
                ("turbidity", models.FloatField()),
                ("SS", models.FloatField()),
                ("NH3_H", models.FloatField()),
                ("NO2_H", models.FloatField()),
                ("NO3_H", models.FloatField()),
                ("PO4_P", models.FloatField()),
                ("TBC", models.FloatField()),
                ("vibrio", models.FloatField(blank=True, null=True)),
                ("COD", models.FloatField(blank=True, null=True)),
                ("MBAS", models.FloatField(blank=True, null=True)),
                ("TOC", models.FloatField(blank=True, null=True)),
                ("lipid", models.FloatField(blank=True, null=True)),
                ("BOD5", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "WaterData",
            },
        ),
    ]
