# Generated by Django 4.1.1 on 2023-08-10 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_waterdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="HabitatData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataID", models.CharField(max_length=255)),
                ("eventID", models.CharField(max_length=255)),
                ("time", models.DateField()),
                ("season", models.CharField(max_length=255)),
                ("river", models.CharField(max_length=255)),
                ("locationID", models.CharField(max_length=255)),
                ("factor", models.CharField(max_length=255)),
                ("score", models.IntegerField()),
                ("samplingProtocol", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "HabitatData",
            },
        ),
    ]
