# Generated by Django 4.1.1 on 2023-08-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_habitatdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoralCommData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataID", models.CharField(max_length=50)),
                ("eventID", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("day", models.IntegerField()),
                ("time", models.DateField()),
                ("locationID", models.CharField(max_length=50)),
                ("verbatimLocality", models.CharField(max_length=50)),
                ("locality", models.CharField(max_length=50)),
                ("verbatimDepth", models.CharField(max_length=50)),
                (
                    "decimalLatitude",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                (
                    "decimalLongitude",
                    models.DecimalField(decimal_places=8, max_digits=10),
                ),
                ("replicate", models.IntegerField()),
                ("Benthic_group", models.CharField(max_length=255)),
                ("Benthic_subgroup", models.CharField(max_length=255)),
                ("coverInPercentage", models.FloatField()),
                ("Field_codes_on_CPCe", models.CharField(max_length=255)),
                ("samplingProtocol", models.CharField(max_length=255)),
                ("sampleSizeValue", models.IntegerField()),
                ("sampleSizeUnit", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "CoralCommData",
            },
        ),
    ]
