# Generated by Django 4.1.1 on 2023-08-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_coralcommdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coralcommdata",
            name="replicate",
            field=models.CharField(max_length=255),
        ),
    ]
