# Generated by Django 4.2 on 2023-08-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_coralcommdata_replicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishdata',
            name='time',
            field=models.DateField(),
        ),
    ]
