# Generated by Django 4.2 on 2023-08-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_fishdata_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('eventID', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('locationID', models.CharField(max_length=255)),
                ('verbatimLocality', models.CharField(max_length=255)),
                ('is_local_villager', models.CharField(max_length=255)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('preferable_site', models.CharField(blank=True, max_length=255, null=True)),
                ('catchment_individuals_per_month', models.CharField(blank=True, max_length=255, null=True)),
                ('fishing_feq', models.CharField(blank=True, max_length=255, null=True)),
                ('fishing_method', models.CharField(blank=True, max_length=255, null=True)),
                ('bait', models.CharField(blank=True, max_length=255, null=True)),
                ('fish_species', models.CharField(blank=True, max_length=255, null=True)),
                ('feel_size_decrease', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'FishingData',
            },
        ),
    ]
