# Generated by Django 4.1.1 on 2023-08-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_fishingdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="OceanSoundIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataID", models.CharField(max_length=255)),
                ("eventID", models.CharField(max_length=255)),
                ("time", models.DateTimeField()),
                ("kHz0_24", models.FloatField()),
                ("lower_200Hz", models.FloatField()),
                ("Hz200_1500", models.FloatField()),
                ("higher_1500Hz", models.FloatField()),
            ],
            options={
                "db_table": "OceanSoundIndex",
            },
        ),
    ]
