# Generated by Django 4.1.1 on 2023-08-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_oceansoundindex"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OceanSoundIndex",
            new_name="OceanSoundIndexData",
        ),
    ]
