# Generated by Django 4.1.1 on 2023-08-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_rename_oceansoundindex_oceansoundindexdata"),
    ]

    operations = [
        migrations.CreateModel(
            name="BioSoundBS2023",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataID", models.CharField(max_length=255)),
                ("eventID", models.CharField(max_length=255)),
                ("classid", models.IntegerField()),
                ("scientificName", models.CharField(max_length=255)),
                ("taxonRank", models.CharField(max_length=255)),
                ("vernacularName", models.CharField(max_length=255)),
                ("soundclass", models.CharField(max_length=255)),
                ("time_begin", models.IntegerField()),
                ("time_end", models.IntegerField()),
                ("confidence", models.FloatField()),
                ("associatedMedia", models.CharField(max_length=255)),
                ("freq_low", models.IntegerField()),
                ("freq_high", models.IntegerField()),
                ("time", models.DateTimeField()),
            ],
            options={
                "db_table": "BioSoundBS2023",
            },
        ),
        migrations.CreateModel(
            name="BioSoundGST2023",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataID", models.CharField(max_length=255)),
                ("eventID", models.CharField(max_length=255)),
                ("classid", models.IntegerField()),
                ("scientificName", models.CharField(max_length=255)),
                ("taxonRank", models.CharField(max_length=255)),
                ("vernacularName", models.CharField(max_length=255)),
                ("soundclass", models.CharField(max_length=255)),
                ("time_begin", models.IntegerField()),
                ("time_end", models.IntegerField()),
                ("confidence", models.FloatField()),
                ("associatedMedia", models.CharField(max_length=255)),
                ("freq_low", models.IntegerField()),
                ("freq_high", models.IntegerField()),
                ("time", models.DateTimeField()),
            ],
            options={
                "db_table": "BioSoundGST2023",
            },
        ),
        migrations.CreateModel(
            name="BioSoundLH2023",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataID", models.CharField(max_length=255)),
                ("eventID", models.CharField(max_length=255)),
                ("classid", models.IntegerField()),
                ("scientificName", models.CharField(max_length=255)),
                ("taxonRank", models.CharField(max_length=255)),
                ("vernacularName", models.CharField(max_length=255)),
                ("soundclass", models.CharField(max_length=255)),
                ("time_begin", models.IntegerField()),
                ("time_end", models.IntegerField()),
                ("confidence", models.FloatField()),
                ("associatedMedia", models.CharField(max_length=255)),
                ("freq_low", models.IntegerField()),
                ("freq_high", models.IntegerField()),
                ("time", models.DateTimeField()),
            ],
            options={
                "db_table": "BioSoundLH2023",
            },
        ),
        migrations.CreateModel(
            name="BioSoundYZH2023",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dataID", models.CharField(max_length=255)),
                ("eventID", models.CharField(max_length=255)),
                ("classid", models.IntegerField()),
                ("scientificName", models.CharField(max_length=255)),
                ("taxonRank", models.CharField(max_length=255)),
                ("vernacularName", models.CharField(max_length=255)),
                ("soundclass", models.CharField(max_length=255)),
                ("time_begin", models.IntegerField()),
                ("time_end", models.IntegerField()),
                ("confidence", models.FloatField()),
                ("associatedMedia", models.CharField(max_length=255)),
                ("freq_low", models.IntegerField()),
                ("freq_high", models.IntegerField()),
                ("time", models.DateTimeField()),
            ],
            options={
                "db_table": "BioSoundYZH2023",
            },
        ),
    ]
