# Generated by Django 4.1.1 on 2023-09-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_biosoundbs2023_biosoundgst2023_biosoundlh2023_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantdata",
            name="locationID",
            field=models.CharField(max_length=50),
        ),
    ]
