# Generated by Django 4.2 on 2023-09-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_aquaticfaunadata_streamdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aquaticfaunadata',
            old_name='Abundance',
            new_name='abundance',
        ),
        migrations.RenameField(
            model_name='aquaticfaunadata',
            old_name='AbundanceUnit',
            new_name='abundanceUnit',
        ),
        migrations.RenameField(
            model_name='aquaticfaunadata',
            old_name='Family',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='aquaticfaunadata',
            old_name='Month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='aquaticfaunadata',
            old_name='Phylum',
            new_name='phylum',
        ),
        migrations.RenameField(
            model_name='aquaticfaunadata',
            old_name='Year',
            new_name='year',
        ),
    ]
