# Generated by Django 4.1.1 on 2023-10-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_rename_abundance_aquaticfaunadata_abundance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aquaticfaunadata",
            name="informationWithheld",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
