# Generated by Django 4.2 on 2023-10-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_aquaticfaunadata_informationwithheld'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationTableInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=10, unique=True)),
                ('name_en', models.CharField(max_length=100)),
                ('name_zh', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'LocationTableInfo',
            },
        ),
    ]
