# Generated by Django 4.1.1 on 2023-11-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_locationtableinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoralCommDataField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("field_type", models.CharField(max_length=100)),
                ("title_zh_tw", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255)),
                ("content_zh_tw", models.TextField()),
                ("content_en", models.TextField()),
                ("show", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "CoralCommDataField",
            },
        ),
    ]
