# Generated by Django 4.1.1 on 2023-11-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_coralcommdatafield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coralcommdatafield",
            name="content_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="coralcommdatafield",
            name="content_zh_tw",
            field=models.TextField(blank=True, null=True),
        ),
    ]
