# Generated by Django 4.1.1 on 2023-11-07 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_alter_coralcommdatafield_content_en_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterDataField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                ("field_type", models.CharField(max_length=100)),
                ("title_zh_tw", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255)),
                ("content_zh_tw", models.TextField(blank=True, null=True)),
                ("content_en", models.TextField(blank=True, null=True)),
                ("show", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "WaterDataField",
            },
        ),
    ]
