# Generated by Django 4.1.1 on 2023-11-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_weatherdatafield"),
    ]

    operations = [
        migrations.RenameField(
            model_name="waterdata",
            old_name="DO",
            new_name="Lipid",
        ),
        migrations.RemoveField(
            model_name="waterdata",
            name="lipid",
        ),
    ]
