# Generated by Django 4.2 on 2023-11-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_plantdatafield'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdNetSoundDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
                ('title_zh_tw', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('content_zh_tw', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'BirdNetSoundDataField',
            },
        ),
        migrations.CreateModel(
            name='FishingDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
                ('title_zh_tw', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('content_zh_tw', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'FishingDataField',
            },
        ),
    ]
