# Generated by Django 4.1.1 on 2024-08-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_aquaticfaunadatafield_biosounddatafield_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtolithData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('eventID', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=50)),
                ('genus', models.CharField(max_length=50)),
                ('scientificName', models.CharField(max_length=50)),
                ('taxonRank', models.CharField(max_length=50)),
                ('geologicalAge', models.CharField(max_length=50)),
                ('locationID', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('samplingProtocol', models.CharField(max_length=255)),
                ('typeStatus', models.CharField(max_length=50)),
                ('recordNumber', models.CharField(max_length=255)),
                ('recordedBy', models.CharField(max_length=50)),
                ('identifiedBy', models.CharField(max_length=50)),
                ('individualCount', models.IntegerField()),
                ('verbatimDepth', models.FloatField()),
            ],
            options={
                'db_table': 'OtolithData',
            },
        ),
        migrations.CreateModel(
            name='OtolithDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
                ('title_zh_tw', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('content_zh_tw', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'OtolithDataField',
            },
        ),
    ]
