# Generated by Django 4.1.1 on 2024-08-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_otolithdata_otolithdatafield'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoralDivData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('eventID', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('locationID', models.CharField(max_length=50)),
                ('verbatimLocality', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=255)),
                ('decimalLatitude', models.FloatField()),
                ('decimalLongitude', models.FloatField()),
                ('verbatimDepth', models.FloatField()),
                ('samplingProtocol', models.CharField(max_length=255)),
                ('sampleSizeValue', models.FloatField()),
                ('sampleSizeUnit', models.CharField(max_length=50)),
                ('kingdom', models.CharField(max_length=50)),
                ('phylum', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100, null=True)),
                ('genus', models.CharField(max_length=50)),
                ('specificEpithet', models.CharField(max_length=50)),
                ('occurrenceStatus', models.CharField(max_length=50)),
                ('scientificName', models.CharField(max_length=50)),
                ('taxonRank', models.CharField(max_length=50)),
                ('abundance', models.FloatField()),
                ('recordedBy', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CoralDivData',
            },
        ),
        migrations.CreateModel(
            name='CoralDivDataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(max_length=100)),
                ('title_zh_tw', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255)),
                ('content_zh_tw', models.TextField(blank=True, null=True)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'CoralDivDataField',
            },
        ),
    ]
