# Generated by Django 4.1.1 on 2024-09-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_coralbleachdata_coralbleachdatafield'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorabiliaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='social_observation__images/')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'memorabilia_content',
            },
        ),
    ]
