# Generated by Django 4.1.1 on 2024-09-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_memorabiliacontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='social_observation__images/')),
                ('description', models.TextField(null=True)),
                ('content', models.TextField(null=True)),
            ],
            options={
                'db_table': 'land_usage',
            },
        ),
    ]
