# Generated by Django 4.1.1 on 2024-09-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_landusage_content_alter_landusage_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OceanUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='social_observation__images/')),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('content', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'db_table': 'ocean_usage',
            },
        ),
    ]
