# Generated by Django 4.1.1 on 2024-09-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_fishdata_bodylength_alter_fishdata_eventid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coralcommdata',
            name='Benthic_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='Benthic_subgroup',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='Field_codes_on_CPCe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='coverInPercentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='decimalLatitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='decimalLongitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='eventID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='locality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='locationID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='replicate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='sampleSizeUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='sampleSizeValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='samplingProtocol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='verbatimDepth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='verbatimLocality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='coralcommdata',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
