# Generated by Django 4.1.1 on 2024-09-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_alter_coralcommdata_benthic_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coralcommdata',
            name='decimalLongitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
    ]
