# Generated by Django 4.1.1 on 2024-09-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_alter_coralcommdata_decimallongitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='class_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='class_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='dataID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='day_or_night',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='eventID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='family_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='habitat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='individualCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='informationWithheld',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='locationID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='phylum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='phylum_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='river',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='samplingProtocol',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='scientificName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='surveyObject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='surveyObjectID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='taxonRank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='vernacularName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zoobenthosdata',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
