# Generated by Django 4.1.1 on 2024-09-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_alter_zoobenthosdata_class_c_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='coordinatePrecision',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='decimalLatitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='decimalLongitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='eventID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='family',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='habitat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='identifiedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='layer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='locationID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='measurementDeterminedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='measurementType',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='measurementUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='measurementValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='recordedBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='sampleSizeUnit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='sampleSizeValue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='samplingProtocol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='scientificName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='taxonRank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='verbatimElevation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='vernacularName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
