# Generated by Django 4.1.1 on 2024-09-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_plantdata_coordinateprecision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='dataID',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='eventID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='measurementDeterminedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
