# Generated by Django 4.1.1 on 2024-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_alter_plantdata_scientificname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='scientificName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
