# Generated by Django 4.1.1 on 2024-09-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_plantdata_scientificname'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerreSoundIndexData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=200)),
                ('eventID', models.CharField(blank=True, max_length=200, null=True)),
                ('locationID', models.CharField(blank=True, max_length=10, null=True)),
                ('sh', models.FloatField(blank=True, null=True)),
                ('th', models.FloatField(blank=True, null=True)),
                ('H', models.FloatField(blank=True, null=True)),
                ('ACI', models.FloatField(blank=True, null=True)),
                ('ADI', models.FloatField(blank=True, null=True)),
                ('AEI', models.FloatField(blank=True, null=True)),
                ('BI', models.FloatField(blank=True, null=True)),
                ('NDSI', models.FloatField(blank=True, null=True)),
                ('associatedMedia', models.CharField(blank=True, max_length=200, null=True)),
                ('min', models.FloatField(blank=True, null=True)),
                ('sec', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TerreSoundIndexData',
            },
        ),
    ]
