# Generated by Django 4.1.1 on 2024-09-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_terresoundindexdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirdNetSoundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('eventID', models.CharField(blank=True, max_length=255, null=True)),
                ('locationID', models.CharField(blank=True, max_length=10, null=True)),
                ('species_list', models.CharField(blank=True, max_length=255, null=True)),
                ('scientificName', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonRank', models.CharField(blank=True, max_length=255, null=True)),
                ('vernacularName', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('time_begin', models.IntegerField(blank=True, null=True)),
                ('time_end', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('associatedMedia', models.CharField(blank=True, max_length=255, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('overlap', models.IntegerField(blank=True, null=True)),
                ('sensitivity', models.IntegerField(blank=True, null=True)),
                ('min_conf', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BirdNetSound',
            },
        ),
    ]
