# Generated by Django 4.1.1 on 2024-09-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_birdnetsounddata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='birdnetsounddata',
            table='BirdNetSoundData',
        ),
    ]
