# Generated by Django 4.1.1 on 2024-09-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_birdnetsounddata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='BioSoundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('eventID', models.CharField(blank=True, max_length=255, null=True)),
                ('locationID', models.CharField(blank=True, max_length=10, null=True)),
                ('classid', models.IntegerField(blank=True, null=True)),
                ('scientificName', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonRank', models.CharField(blank=True, max_length=255, null=True)),
                ('vernacularName', models.CharField(blank=True, max_length=255, null=True)),
                ('soundclass', models.CharField(blank=True, max_length=255, null=True)),
                ('time_begin', models.IntegerField(blank=True, null=True)),
                ('time_end', models.IntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('associatedMedia', models.CharField(blank=True, max_length=255, null=True)),
                ('freq_low', models.IntegerField(blank=True, null=True)),
                ('freq_high', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'BioSoundData',
            },
        ),
    ]
