# Generated by Django 4.1.1 on 2024-09-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_biosounddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='abundance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='abundanceUnit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='class_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='class_field',
            field=models.CharField(blank=True, db_column='class', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='eventID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='individualCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='locationID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='phylum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='phylum_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='river',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='samplingProtocol',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='scientificName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='surveyObject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='surveyObjectID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='taxonRank',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='vernacularName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aquaticfaunadata',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
