# Generated by Django 4.1.1 on 2024-09-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_alter_aquaticfaunadata_abundance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceansoundindexdata',
            name='locationID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='oceansoundindexdata',
            name='Hz200_1500',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oceansoundindexdata',
            name='eventID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oceansoundindexdata',
            name='higher_1500Hz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oceansoundindexdata',
            name='kHz0_24',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oceansoundindexdata',
            name='lower_200Hz',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oceansoundindexdata',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
