# Generated by Django 4.1.1 on 2024-09-25 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_oceansoundindexdata_locationid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceansoundindexdata',
            name='verbatimDepth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
