# Generated by Django 4.1.1 on 2024-09-26 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_oceansoundindexdata_verbatimdepth'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oceansoundindexdata',
            table='OceanSoundIndexData',
        ),
    ]
