# Generated by Django 4.1.1 on 2024-12-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_oceansoundindexdata_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingdata',
            name='fish_species',
            field=models.CharField(blank=True, max_length=2550, null=True),
        ),
    ]
