# Generated by Django 4.1.1 on 2024-12-05 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_fishingdata_fish_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterdata',
            name='NH3_H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='NO2_H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='NO3_H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='PO4_P',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='SS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='TBC',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='conductivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='salinity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='turbidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='verbatimDepth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='waterTemperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
