# Generated by Django 4.1.1 on 2024-12-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_alter_waterdata_nh3_h_alter_waterdata_no2_h_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='windDirection',
            field=models.FloatField(),
        ),
    ]
