# Generated by Django 4.1.1 on 2024-12-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_alter_weatherdata_winddirection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='PAR',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
