# Generated by Django 4.1.1 on 2024-12-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_weatherdata_rh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatemperatureck2023',
            name='fieldNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seatemperaturedbs2023',
            name='fieldNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seatemperaturegg2023',
            name='fieldNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seatemperaturegw2023',
            name='fieldNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seatemperaturenl2023',
            name='fieldNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seatemperaturesl2023',
            name='fieldNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seatemperaturewqg2023',
            name='fieldNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seatemperatureyzh2023',
            name='fieldNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seatemperaturezp2023',
            name='fieldNumber',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
