# Generated by Django 4.1.1 on 2024-12-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_alter_seatemperatureck2023_fieldnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamdata',
            name='BOD5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='DO',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='NH3_H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='NO2_H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='NO3_H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='PO4_P',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='RPI_Level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='RPI_Score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='SS',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='conductivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='pH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='salinity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamdata',
            name='waterTemperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
