# Generated by Django 4.1.1 on 2024-12-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_alter_streamdata_bod5_alter_streamdata_do_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeaTemperatureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('eventID', models.CharField(max_length=255)),
                ('resourceName', models.CharField(max_length=255)),
                ('locationID', models.CharField(max_length=255)),
                ('verbatimDepth', models.CharField(max_length=255)),
                ('fieldNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.DateTimeField()),
                ('seaTemperature', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'SeaTemperatureData',
            },
        ),
    ]
