# Generated by Django 4.1.1 on 2024-12-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_seatemperaturedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.CharField(max_length=255)),
                ('time', models.DateField()),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('CAP_issue', models.CharField(max_length=255)),
                ('local_issue', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('participant_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'social_interview',
            },
        ),
    ]
