# Generated by Django 4.1.1 on 2025-01-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_socialinterview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialinterview',
            name='CAP_issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialinterview',
            name='local_issue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialinterview',
            name='participant_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialinterview',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
