# Generated by Django 4.1.1 on 2025-01-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_alter_socialinterview_cap_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialinterview',
            name='time',
            field=models.TextField(),
        ),
    ]
