# Generated by Django 4.1.1 on 2025-01-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_alter_socialinterview_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInterviewCapIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_issue', models.CharField(blank=True, max_length=255, null=True)),
                ('cap_issue_mandarin', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'social_interview_cap_issues',
            },
        ),
    ]
