# Generated by Django 4.1.1 on 2025-03-21 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_socialinterviewcapissues'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasetID', models.CharField(blank=True, max_length=255, null=True)),
                ('datasetName', models.CharField(blank=True, max_length=255, null=True)),
                ('datasetStartDate', models.DateField(blank=True, null=True)),
                ('datasetEndDate', models.DateField(blank=True, null=True)),
                ('occurrenceCount', models.IntegerField(blank=True, null=True)),
                ('resourceContacts', models.CharField(blank=True, max_length=255, null=True)),
                ('datasetLicense', models.CharField(blank=True, max_length=255, null=True)),
                ('created', models.DateField(blank=True, null=True)),
                ('modified', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
