# Generated by Django 4.1.1 on 2025-03-21 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_datasetsummary'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='datasetsummary',
            table='dataset_summary',
        ),
    ]
