# Generated by Django 4.1.1 on 2025-03-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_alter_datasetsummary_datasetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsummary',
            name='datasetName',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
