# Generated by Django 4.1.1 on 2025-03-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_alter_datasetsummary_datasetname'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetsummary',
            name='datasetURL',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datasetsummary',
            name='datasetName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
