# Generated by Django 4.1.1 on 2025-03-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_datasetsummary_dataseturl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetsummary',
            name='datasetURL',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
