# Generated by Django 4.1.1 on 2025-03-24 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_alter_datasetsummary_dataseturl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coraldata',
            name='decimalLongitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
