# Generated by Django 4.1.1 on 2025-07-14 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_buoydata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_direction_cell_1',
            new_name='current_direction_1',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_direction_cell_10',
            new_name='current_direction_10',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_direction_cell_2',
            new_name='current_direction_2',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_direction_cell_3',
            new_name='current_direction_3',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_direction_cell_4',
            new_name='current_direction_4',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_direction_cell_5',
            new_name='current_direction_5',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_direction_cell_6',
            new_name='current_direction_6',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_direction_cell_7',
            new_name='current_direction_7',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_direction_cell_8',
            new_name='current_direction_8',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_direction_cell_9',
            new_name='current_direction_9',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_speed_cell_1',
            new_name='current_speed_1',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_speed_cell_10',
            new_name='current_speed_10',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_speed_cell_2',
            new_name='current_speed_2',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_speed_cell_3',
            new_name='current_speed_3',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_speed_cell_4',
            new_name='current_speed_4',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_speed_cell_5',
            new_name='current_speed_5',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_speed_cell_6',
            new_name='current_speed_6',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_speed_cell_7',
            new_name='current_speed_7',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_speed_cell_8',
            new_name='current_speed_8',
        ),
        migrations.RenameField(
            model_name='buoydata',
            old_name='current_speed_cell_9',
            new_name='current_speed_9',
        ),
    ]
