# Generated by Django 4.1.1 on 2025-07-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_rename_current_direction_cell_1_buoydata_current_direction_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buoydata',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
