# Generated by Django 4.1.1 on 2025-07-14 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_buoydatafield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuoyDataField',
            new_name='BuoyHistoricalDataField',
        ),
        migrations.AlterModelTable(
            name='buoyhistoricaldatafield',
            table='BuoyHistoricalDataField',
        ),
    ]
