# Generated by Django 4.1.1 on 2026-01-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_buoyrealtimedatafield'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterdata',
            name='DO',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waterdata',
            name='pH',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
