# Generated by Django 4.1.1 on 2026-01-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_waterdata_do_waterdata_created_at_waterdata_ph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterdata',
            name='data_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='waterdata',
            name='dataID',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
