# Generated by Django 4.1.1 on 2026-01-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_zoobenthosdata_created_at_zoobenthosdata_data_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='terresoundindexdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terresoundindexdata',
            name='data_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terresoundindexdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
