# Generated by Django 4.1.1 on 2026-01-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_fishdata_created_at_fishdata_data_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishdata',
            name='region',
        ),
        migrations.RemoveField(
            model_name='fishdata',
            name='year',
        ),
        migrations.AlterField(
            model_name='fishdata',
            name='eventID',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fishdata',
            name='locationID',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fishdata',
            name='samplingProtocol',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
