# Generated by Django 4.1.1 on 2026-01-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_fishingdata_created_at_fishingdata_data_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingdata',
            name='feel_size_decrease',
            field=models.BooleanField(blank=True, max_length=255, null=True),
        ),
    ]
