# Generated by Django 4.1.1 on 2026-01-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_weatherdata_created_at_weatherdata_data_hash_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeaTemperatureCK2023',
        ),
        migrations.DeleteModel(
            name='SeaTemperatureDBS2023',
        ),
        migrations.DeleteModel(
            name='SeaTemperatureGG2023',
        ),
        migrations.DeleteModel(
            name='SeaTemperatureGW2023',
        ),
        migrations.DeleteModel(
            name='SeaTemperatureNL2023',
        ),
        migrations.DeleteModel(
            name='SeaTemperatureSL2023',
        ),
        migrations.DeleteModel(
            name='SeaTemperatureWQG2023',
        ),
        migrations.DeleteModel(
            name='SeaTemperatureYZH2023',
        ),
        migrations.DeleteModel(
            name='SeaTemperatureZP2023',
        ),
        migrations.AddField(
            model_name='seatemperaturedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seatemperaturedata',
            name='data_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seatemperaturedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
