# Generated by Django 4.1.1 on 2026-01-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_delete_seatemperatureck2023_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birdnetsounddata',
            name='min_conf',
        ),
        migrations.RemoveField(
            model_name='birdnetsounddata',
            name='overlap',
        ),
        migrations.RemoveField(
            model_name='birdnetsounddata',
            name='sensitivity',
        ),
        migrations.RemoveField(
            model_name='birdnetsounddata',
            name='species_list',
        ),
        migrations.RemoveField(
            model_name='birdnetsounddata',
            name='week',
        ),
        migrations.AddField(
            model_name='birdnetsounddata',
            name='birdnet2_4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='birdnetsounddata',
            name='family',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='birdnetsounddata',
            name='familyChinese',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='birdnetsounddata',
            name='scientificNameID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='birdnetsounddata',
            name='taxonID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='birdnetsounddata',
            name='eventID',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='birdnetsounddata',
            name='scientificName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
