# Generated by Django 4.1.1 on 2026-01-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_remove_birdnetsounddata_min_conf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishingdata',
            name='feel_size_decrease',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
