# Generated by Django 4.1.1 on 2026-02-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_alter_fishingdata_feel_size_decrease'),
    ]

    operations = [
        migrations.AddField(
            model_name='oceansoundindexdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oceansoundindexdata',
            name='data_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oceansoundindexdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
