# Generated by Django 4.1.1 on 2026-03-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_iptaquaticfaunaevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iptaquaticfaunaevent',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='iptaquaticfaunaevent',
            name='content_zh_tw',
        ),
        migrations.RemoveField(
            model_name='iptaquaticfaunaevent',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='iptaquaticfaunaevent',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='iptaquaticfaunaevent',
            name='show',
        ),
        migrations.RemoveField(
            model_name='iptaquaticfaunaevent',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='iptaquaticfaunaevent',
            name='title_zh_tw',
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='countryCode',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='decimalLatitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='decimalLongitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='eventDate',
            field=models.CharField(default='2026-01-01', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='eventID',
            field=models.CharField(default='event_1', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='geodeticDatum',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='locationID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='municipality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='sampleSizeUnit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='sampleSizeValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='samplingEffort',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='samplingProtocol',
            field=models.CharField(default='protocol', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iptaquaticfaunaevent',
            name='verbatimLocality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
