# Generated by Django 4.1.1 on 2026-05-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_remove_iptaquaticfaunaevent_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IptAquaticfaunaOccurrenceExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrenceID', models.CharField(max_length=255, unique=True)),
                ('eventID', models.CharField(max_length=255)),
                ('basisOfRecord', models.CharField(max_length=50)),
                ('scientificName', models.CharField(max_length=255)),
                ('individualCount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ipt_aquaticfauna_occurrence_extension',
            },
        ),
    ]
