# Generated by Codex on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0125_iptaquaticfaunaoccurrenceextension"),
    ]

    operations = [
        migrations.AddField(
            model_name="iptaquaticfaunaoccurrenceextension",
            name="decimalLatitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="iptaquaticfaunaoccurrenceextension",
            name="decimalLongitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
