# Generated by Codex on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0126_iptaquaticfaunaoccurrenceextension_decimallatitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="iptaquaticfaunaoccurrenceextension",
            name="kingdom",
            field=models.CharField(default="Animalia", max_length=255),
        ),
        migrations.AddField(
            model_name="iptaquaticfaunaoccurrenceextension",
            name="phylum",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="iptaquaticfaunaoccurrenceextension",
            name="class_field",
            field=models.CharField(
                blank=True, db_column="class", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="iptaquaticfaunaoccurrenceextension",
            name="order",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="iptaquaticfaunaoccurrenceextension",
            name="family",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="iptaquaticfaunaoccurrenceextension",
            name="genus",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="iptaquaticfaunaoccurrenceextension",
            name="taxonRank",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="iptaquaticfaunaoccurrenceextension",
            name="parentNameUsageID",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
