# Generated by Django 4.1.1 on 2026-05-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0127_iptaquaticfaunaoccurrenceextension_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptaquaticfaunaoccurrenceextension',
            name='eventDate',
            field=models.CharField(default='2026-01-01', max_length=50),
            preserve_default=False,
        ),
    ]
