# Generated by Django 4.1.1 on 2026-06-03 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0128_iptaquaticfaunaoccurrenceextension_eventdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iptaquaticfaunaoccurrenceextension',
            old_name='parentNameUsageID',
            new_name='acceptedNameUsageID',
        ),
    ]
