# Generated by Django 4.1.1 on 2026-06-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0129_rename_parentnameusageid_iptaquaticfaunaoccurrenceextension_acceptednameusageid'),
    ]

    operations = [
        migrations.CreateModel(
            name='IptPlantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=255, unique=True)),
                ('eventDate', models.CharField(max_length=50)),
                ('samplingProtocol', models.CharField(max_length=255)),
                ('sampleSizeValue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sampleSizeUnit', models.CharField(blank=True, max_length=255, null=True)),
                ('samplingEffort', models.CharField(blank=True, max_length=255, null=True)),
                ('locationID', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('countryCode', models.CharField(blank=True, max_length=2, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('verbatimLocality', models.CharField(blank=True, max_length=255, null=True)),
                ('decimalLatitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('decimalLongitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geodeticDatum', models.CharField(blank=True, max_length=50, null=True)),
                ('coordinatePrecision', models.FloatField(blank=True, null=True)),
                ('verbatimElevation', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ipt_plant_event',
            },
        ),
        migrations.CreateModel(
            name='IptPlantMeasurementOrFactExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.CharField(max_length=255, unique=True)),
                ('eventDate', models.CharField(max_length=50)),
                ('samplingProtocol', models.CharField(max_length=255)),
                ('sampleSizeValue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sampleSizeUnit', models.CharField(blank=True, max_length=255, null=True)),
                ('samplingEffort', models.CharField(blank=True, max_length=255, null=True)),
                ('locationID', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('countryCode', models.CharField(blank=True, max_length=2, null=True)),
                ('county', models.CharField(blank=True, max_length=100, null=True)),
                ('municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=255, null=True)),
                ('verbatimLocality', models.CharField(blank=True, max_length=255, null=True)),
                ('decimalLatitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('decimalLongitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('geodeticDatum', models.CharField(blank=True, max_length=50, null=True)),
                ('measurementDeterminedDate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'ipt_plant_measurement_or_fact_extension',
            },
        ),
        migrations.CreateModel(
            name='IptPlantOccurrenceExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrenceID', models.CharField(max_length=255, unique=True)),
                ('eventID', models.CharField(max_length=255)),
                ('basisOfRecord', models.CharField(max_length=50)),
                ('scientificName', models.CharField(max_length=255)),
                ('individualCount', models.IntegerField(blank=True, null=True)),
                ('decimalLatitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('decimalLongitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('eventDate', models.CharField(max_length=50)),
                ('kingdom', models.CharField(default='Plantae', max_length=255)),
                ('phylum', models.CharField(blank=True, max_length=255, null=True)),
                ('class_field', models.CharField(blank=True, db_column='class', max_length=255, null=True)),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('family', models.CharField(blank=True, max_length=255, null=True)),
                ('genus', models.CharField(blank=True, max_length=255, null=True)),
                ('taxonRank', models.CharField(blank=True, max_length=255, null=True)),
                ('acceptedNameUsageID', models.CharField(blank=True, max_length=255, null=True)),
                ('recordedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('identifiedBy', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ipt_plant_occurrence_extension',
            },
        ),
    ]
