# Generated by Django 4.1.1 on 2026-06-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0131_fix_ipt_plant_measurement_or_fact_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='iptplantmeasurementorfactextension',
            name='eventID',
            field=models.CharField(default='2026-06-23', max_length=255),
            preserve_default=False,
        ),
    ]
